# Generated by Django 4.2.2 on 2023-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_expensecategory_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
